services:
  postgres-service:
    image: postgres:16-alpine
    container_name: postgres_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphBlog

    ports:
      - "5433:5432"

    volumes:
      - ./migration/001_create_users.up.sql:/docker-entrypoint-initdb.d/001_create_users.sql
      - ./migration/002_create_posts.up.sql:/docker-entrypoint-initdb.d/002_create_posts.sql
      - ./migration/003_create_comments.up.sql:/docker-entrypoint-initdb.d/003_create_comments.sql

  app:
    build: ./
    container_name: graphql_blog_app

    environment:
      REPOSITORY_TYPE: ${REPOSITORY_TYPE:-memory}
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8080:8080"

    depends_on:
      - postgres-service

    restart: on-failure