version: "3.8"

services:
  postgres-service:
    image: postgres:16-alpine
    container_name: postgres_db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${graphBlog}

    ports:
      - "5432:5432"

    volumes:
      - ./migration/001_create_users.up.sql:/docker-entrypoint-initdb.d/001_create_users.sql
      - ./migration/002_create_posts.up.sql:/docker-entrypoint-initdb.d/002_create_posts.sql
      - ./migration/003_create_comments.up.sql:/docker-entrypoint-initdb.d/003_create_comments.sql

  app:
    build: ./
    container_name: graphql_blog_app

    environment:
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8080:8080"

    depends_on:
      - postgres-service

    restart: on-failure