// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	Post     *Post      `json:"post"`
	Author   *User      `json:"author"`
	Content  string     `json:"content"`
	Parent   *Comment   `json:"parent,omitempty"`
	Children []*Comment `json:"children"`
}

type CommentConnection struct {
	Items    []*Comment `json:"items"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type CommentsPagination struct {
	Limit  *int    `json:"limit,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Content  string  `json:"content"`
}

type CreatePostInput struct {
	Content string `json:"content"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID              string `json:"id"`
	Content         string `json:"content"`
	Author          *User  `json:"author"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID    string  `json:"id"`
	Posts []*Post `json:"posts"`
}
